[package]
name = "memory-lol-web"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
chrono = { workspace = true }
indexmap = { version = "2", features = ["serde"] }
egg-mode = "0.16"
log = "0.4"
memory-lol = { path = "../core" }
memory-lol-auth = { path = "../auth" }
memory-lol-auth-sqlx = { path = "../auth-sqlx" }
rocket = { git = "https://github.com/rwf2/Rocket.git", rev = "3a54d079aef060a8f732bd04ea54b0581a604087", features = ["json"] }
rocket_oauth2 = { git = "https://github.com/travisbrown/rocket_oauth2.git", rev = "e49c62a313d541d0681344f88715e94d2c621f5f" }
rocket_db_pools = { git = "https://github.com/rwf2/Rocket.git", rev = "3a54d079aef060a8f732bd04ea54b0581a604087", features = ["sqlx_sqlite"] }
rocksdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
